local _, Cortex = ...

local Constants = {
    VERSION = "0.1.0",
    ACCOUNT_SCHEMA_VERSION = 2,
    CHARACTER_SCHEMA_VERSION = 1,
    GOAL_SCHEMA_VERSION = 1,
    CHARACTER_RECORD_SCHEMA_VERSION = 1,
    LOG_LEVELS = {
        ERROR = 1,
        WARN = 2,
        INFO = 3,
        DEBUG = 4,
        TRACE = 5,
    },
    EVENTS = {
        ADDON_INITIALIZED = "CORTEX_ADDON_INITIALIZED",
        PLAYER_LOGIN = "CORTEX_PLAYER_LOGIN",
        PLAYER_LOGOUT = "CORTEX_PLAYER_LOGOUT",
        COMBAT_LOCKDOWN_CHANGED = "CORTEX_COMBAT_LOCKDOWN_CHANGED",
        CONTEXT_UPDATED = "CORTEX_CONTEXT_UPDATED",
        FACT_CHANGED = "CORTEX_FACT_CHANGED",
        GOALS_CHANGED = "CORTEX_GOALS_CHANGED",
        RECOMMENDATIONS_INVALIDATED = "CORTEX_RECOMMENDATIONS_INVALIDATED",
        MODULE_STATE_CHANGED = "CORTEX_MODULE_STATE_CHANGED",
        NAVIGATION_CHANGED = "CORTEX_NAVIGATION_CHANGED",
    },
}

Cortex.Constants = Constants
Cortex.version = Constants.VERSION
