local _, Cortex = ...

local Constants = {
    VERSION = "0.1.0-alpha",
    ACCOUNT_SCHEMA_VERSION = 7,
    CHARACTER_SCHEMA_VERSION = 1,
    GOAL_SCHEMA_VERSION = 2,
    GOALS_SCHEMA_VERSION = 2,
    CHARACTER_RECORD_SCHEMA_VERSION = 2,
    WARBAND_SNAPSHOT_SCHEMA_VERSION = 1,
    SESSION_SNAPSHOT_SCHEMA_VERSION = 1,
    MAX_HISTORY_ENTRIES = 50,
    MAX_SNAPSHOT_REFERENCES = 50,
    MAX_WARBAND_CURRENCIES = 32,
    SHARE_CODE_FORMAT_VERSION = 1,
    MAX_SHARE_CODE_BYTES = 12288,
    MAX_SHARE_PAYLOAD_BYTES = 8192,
    MAX_SHARE_STRING_BYTES = 1024,
    MAX_SHARE_NODES = 512,
    MAX_SHARE_DEPTH = 8,
    MAX_SHARE_TASKS = 50,
    MAX_SHARE_TEMPLATES = 50,
    LOG_LEVELS = {
        ERROR = 1,
        WARN = 2,
        INFO = 3,
        DEBUG = 4,
        TRACE = 5,
    },
    GOAL_STATUSES = {
        ACTIVE = "ACTIVE",
        BLOCKED = "BLOCKED",
        COMPLETED = "COMPLETED",
        PAUSED = "PAUSED",
        FAILED = "FAILED",
    },
    EVENTS = {
        ADDON_INITIALIZED = "CORTEX_ADDON_INITIALIZED",
        PLAYER_LOGIN = "CORTEX_PLAYER_LOGIN",
        PLAYER_LOGOUT = "CORTEX_PLAYER_LOGOUT",
        COMBAT_LOCKDOWN_CHANGED = "CORTEX_COMBAT_LOCKDOWN_CHANGED",
        CONTEXT_UPDATED = "CORTEX_CONTEXT_UPDATED",
        FACT_CHANGED = "CORTEX_FACT_CHANGED",
        GOALS_CHANGED = "CORTEX_GOALS_CHANGED",
        RECOMMENDATIONS_INVALIDATED = "CORTEX_RECOMMENDATIONS_INVALIDATED",
        MODULE_STATE_CHANGED = "CORTEX_MODULE_STATE_CHANGED",
        NAVIGATION_CHANGED = "CORTEX_NAVIGATION_CHANGED",
        WARBAND_UPDATED = "CORTEX_WARBAND_UPDATED",
        DEBRIEF_UPDATED = "CORTEX_DEBRIEF_UPDATED",
    },
}

Cortex.Constants = Constants
Cortex.version = Constants.VERSION
